language: php

sudo: required

services:
  - mysql
  - docker

mysql:
  database: sparql_entity_storage_test
  username: root
  encoding: utf8

jobs:
  include:

    - name: 'PHPCodeSniffer'
      php: 7.4
      env: TEST_SUITE=PHPCodeSniffer

    - name: 'PHPStan'
      php: 7.4
      env: TEST_SUITE=PHPStan DRUPAL=~8.9.20 PHPUNIT=^7

    - name: 'PHPUnit with Drupal 9 on PHP 7.4'
      php: 7.4
      env: TEST_SUITE=PHPUnit DRUPAL=^9.2 PHPUNIT=^9

    - name: 'PHPUnit with Drupal 9 on PHP 8.0'
      php: 8.0
      env: TEST_SUITE=PHPUnit DRUPAL=^9.2 PHPUNIT=^9

    - name: 'PHPUnit with Drupal 9 on PHP 8 nightly'
      php: nightly
      env: TEST_SUITE=PHPUnit DRUPAL=^9.2 PHPUNIT=^9

cache:
  directories:
    - ${HOME}/.composer/cache

before_install:
  - export COMPOSER_MEMORY_LIMIT=2G
  - export SITE_DIR="${TRAVIS_BUILD_DIR}/../testing_site"
  - mkdir "${TRAVIS_BUILD_DIR}/../testing_site"
  # Remove this line to run with Xdebug enabled.
  - phpenv config-rm xdebug.ini || true

script: ${TRAVIS_BUILD_DIR}/tests/travis-ci/scripts/run_tests.sh

notifications:
  email: false
